apiVersion: v1
kind: Pod
metadata:
  name: stress-ng-fit
spec:
  containers:
  - name: stress-ng
    image: polinux/stress
    resources:
      requests:
        cpu: "3"
        memory: "12Gi"
      limits:
        cpu: "3"
        memory: "12Gi"
    command: ["stress"]
    args: ["--cpu", "3", "--vm", "3", "--vm-bytes", "2G", "--timeout", "300s"]
  restartPolicy: Never
