apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service
  labels:
    app: video-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      containers:
      - name: video-service
        image: dhirajsingh6/video-service:0.0.8
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
