apiVersion: v1
kind: Pod
metadata:
  name: mem-stress
  namespace: default
spec:
  containers:
  - name: stress
    image: progrium/stress
    args:
      - "--vm"
      - "2"
      - "--vm-bytes"
      - "500M"
      - "--timeout"
      - "60s"
  restartPolicy: Never
