apiVersion: v1
kind: Pod
metadata:
  name: stress-max
  namespace: default
spec:
  containers:
  - name: stress
    image: progrium/stress
    args:
      - "--cpu"
      - "8"
      - "--vm"
      - "4"
      - "--vm-bytes"
      - "1G"
  restartPolicy: Never
